### ISSUE TITLE
load ckpt training on my daatsets

### ISSUE THREAD

**Issue by ChengWan9** [baegwangbin/surface_normal_uncertainty#11]
Thanks for your great work!But when I trained the model on my custom dataset with --use_baseline&&--loss_fn NLL_ours,and load run with python test.py,it shows:
![1700969159729](https://github.com/baegwangbin/surface_normal_uncertainty/assets/143673887/a12eb985-34dc-4e5d-abcd-51de887d68ff)
How can I solve this?
Thank you.

**Comment by baegwangbin** [comment]
Hi, sorry for the delayed response.

Please try removing --use_baseline

--use_baseline makes the code to use a baseline model architecture, which is different from the model proposed in the paper

**Comment by ChengWan9** [comment]
thanks for your reply
