### ISSUE TITLE
Training on Scannet

### ISSUE THREAD

**Issue by w080707** [baegwangbin/surface_normal_uncertainty#5]
Hello, I didn't find the data loader for Scannet, could I modify the file **dataloader_nyu.py** to load scannet data? Are there any specific modifications required for scannet? Thanks so much.

**Comment by baegwangbin** [comment]
You should multiply the surface normal vector by -1. Besides that, the dataloader can be implemented in the same way.

**Comment by w080707** [comment]
Thanks so much for your reply.
